name: Snapshot Generator

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: Build Snapshot

    steps:
      - name: Checkout Latest Files
        uses: actions/checkout@v2
      - name: Initialize Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Initialize Project
        run: npm install
      - name: Build Project
        run: npm run stage:build
      - name: Generate Snapshot
        run: node ./scripts/update.js
      - name: Apply Changes to Repository
        uses: EndBug/add-and-commit@v6
        with:
          author_name: "Samuel J Voeller"
          author_email: "samuel.voeller@amethyst.live"
          message: "chore: workflow-build(updater) generate_snapshot"
          add: "_snapshot.json"
          push: "origin main -u --force"
          token: ${{ secrets.RW_ACCESS_TOKEN }}
